#!/usr/bin/env python3
"""Select the pages that make up the WCD test-article fixture.

STATUS: stub. The sampling strategy agreed for the fixture (strata, counts,
how pages are drawn) is not yet recorded here; fill in `select()` from the
sampling-strategy conclusions and keep the criteria documented in this
docstring, since the fixture is only reproducible if the selection is.

Contract:
    input   whatever the strategy needs (a site API, a page-metadata Parquet
            from RevisionChest, a category/WikiProject list, …)
    output  fixtures/pages.txt — one page id per line, '#' comments allowed —
            consumed by `wcd fixture-dump`.

Usage:
    python scripts/select_fixture_pages.py -o fixtures/pages.txt
"""
from __future__ import annotations

import argparse
import sys


def select() -> list[tuple[int, str]]:
    """Return (page_id, reason) pairs. Reason is written as a comment for provenance."""
    raise NotImplementedError("sampling strategy not yet encoded; see docstring")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("-o", "--output", default="fixtures/pages.txt")
    args = ap.parse_args(argv)
    rows = select()
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("# generated by scripts/select_fixture_pages.py\n")
        for page_id, reason in rows:
            fh.write(f"{page_id}  # {reason}\n")
    print(f"wrote {len(rows)} pages to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
